name: "Update Language Source"
description: "Update Source files for the scientific python project"
author: "@goanpeca"
inputs:
  source:
    description: "Source path"
    required: true
  destination:
    description: "Destination path"
    required: true
outputs:
  todo:
    description: "TODO"
runs:
  using: "docker"
  image: "Dockerfile"
